[build]
  publish = "public/"
  command = "yarn build"

[build.environment]
  NODE_VERSION = "12" # Node.jsのLTS。End-of-Time: 2022-04-30
  YARN_VERSION = "1.22.4"
  YARN_FLAGS = "--frozen-lockfile --verbose"
